### ISSUE TITLE
Question about enable-auto-merge job

### ISSUE THREAD

**Issue by florianmutter** [suzuki-shunsuke/tfaction-example#2320]
Hey, I don't understand why the `.github/workflows/wc-enable-auto-merge.yaml` workflow is needed. Here is what I understood:

It runs if nothing fails and if the PR is configured to be automatically merged by renovate ("Automerge: enabled"). Then it enables auto merge.

Isn't the exact same thing done by renovate bot itself?

**Comment by suzuki-shunsuke** [comment]
@florianmutter

Sorry for late reply.
I missed this issue.

I wrote the document about this.
https://suzuki-shunsuke.github.io/guide-github-action-renovate/guide#enable-auto-merge-by-github-actions
